DSI-HUG/dejajs-components

src/component/chips/_chips-theme.scss, src/component/chips/chips.component.html, src/component/chips/chips.component.scss, src/component/chips/chips.component.ts, src/component/chips/chips.module.ts, src/component/chips/index.ts, src/component/range/range.component.scss, src/component/select/_select-theme.scss, src/component/select/select.component.html, src/component/select/select.component.scss, src/component/select/select.component.ts, src/component/select/select.module.ts, src/demo-app/select/select-demo.html, src/scss/mixins/_deja-theme.scss
DejaChips added for DejaSelect selected items in multiselect mode.
Now the selected items chips of the multiselect is a separate component. The position can be set
above or below the input.
=> feat(DejaChips): DejaChips added for DejaSelect multi selected items

package.json, src/component/select/select.component.ts, src/demo-app/demo-app-module.ts, src/demo-app/reactive-form/model/action-name.ts, src/demo-app/reactive-form/model/app-state.interface.ts, src/demo-app/reactive-form/model/user.data.ts, src/demo-app/reactive-form/model/user.interface.ts, src/demo-app/reactive-form/model/user.reducer.ts, src/demo-app/reactive-form/reactive-form-demo.ts, src/demo-app/reactive-form/service/user.service.ts
Add ngrx store to the reactive form demo-app
=> ngrx store on reactive form demo-app

CHANGELOG.md, package.json, src/component/code-viewer/code-viewer.component.ts, src/component/markdown/markdown.component.ts, src/polyfills.ts
@DSI-HUG/deja-js 
Quick fix for PRISMJS issue in bundle
=> Publish 2.2.1

demo/app/circular-picker/circular-picker-demo.scss, demo/app/circular-picker/circular-picker-demo.ts, demo/app/common/news-card.component.ts, demo/app/common/news.model.ts, demo/app/grid/grid-demo.scss, demo/app/grid/grid-demo.ts, demo/app/range/range-demo.scss, demo/app/range/range-demo.ts, demo/app/reactive-form/model/user.data.ts, demo/app/reactive-form/model/user.interface.ts, demo/app/reactive-form/reactive-form-demo.ts, demo/app/select/select-demo.ts, demo/app/services/countries.service.ts, demo/app/services/news.service.ts, demo/app/services/people.service.ts, demo/app/tiles/tiles-demo.ts, demo/app/tree-list/tree-list-demo.ts, demo/app/viewport/viewport-demo.scss, demo/app/viewport/viewport-demo.ts, package.json, src/component/message-box/message-box.component.html, src/component/message-box/message-box.component.scss, src/component/message-box/message-box.component.ts, src/component/select/select.component.scss, yarn.lock
Using json-object-mapper for demo
fix (Global) Removed some deep on scss
=> json-object-mapper

src/component/date-selector/date-selector.component.html
fix https://github.com/DSI-HUG/dejajs-components/issues/152
=> fix(DatePicker): button type

demo/app/reactive-form/model/user.data.ts, demo/app/reactive-form/model/user.interface.ts, demo/app/reactive-form/reactive-form-demo.html, demo/app/reactive-form/reactive-form-demo.ts, demo/app/select/select-demo.html, demo/app/select/select-demo.scss, demo/app/select/select-demo.ts, demo/app/select/validators.ts, demo/app/tree-list/tree-list-demo.html, demo/app/tree-list/tree-list-demo.ts, demo/assets/snippets/select-reactive-form-models.md, demo/assets/snippets/select-reactive-form.md, src/common/core/item-list/item-list-base.ts, src/common/core/item-list/item-list.service.ts, src/component/select/readme.md, src/component/select/select.component.ts, src/component/tree-list/tree-list.component.ts
BREAKING CHANGE: 
selectedModel, selectedModels, formControlName:
The type of the value passed as input determines the output type: if input is null, deja-select returns a generic object.
Le type de la valeur passé comme input détermine le type rendu en output: si en première instance on passe null, deja-select retourne un objet générique.
=> feat(DejaSelectComponent) : better support for reactive forms

CHANGELOG.md, package.json
=> Deploy 2.10.0

src/component/chips/chips.component.spec.ts
Add a new test on DejaChipsComponent, it's a beginning, we need to determine our best practices
=> test(DejaChipsComponent): Add unit test on DejaChipsComponent

karma.conf.js, src/component/chips/chips.component.spec.ts
Add some enhancements for Karma Config
- Better summary tests
- No warnings with Material Theme in tests
=> Karma enhancement

src/component/select/select.component.ts
Ensure selection when models setted after selected items
=> DEJS-239 : Fix on DejaSelect

src/component/color-selector/color-selector.component.ts
=> style(ColorPicker) : Delete dev log

src/component/sidenav/sidenav.component.html, src/component/sidenav/sidenav.component.ts
Also fix AOT build for this component
=> feat(SideNav): Add the possibility to specify the header's icon

CHANGELOG.md, package.json, src/common/core/item-list/item-list-base.ts, src/component/data-grid/data-grid.component.ts
=> Deploy 2.22.1

src/component/numeric-stepper/_numeric-stepper-theme.scss
So it gives more points to this style and force the color to display in other applications
=> Adding an !important attribute on the style class off-limits

CHANGELOG.md, demo/package.json, gulpfile.js, package.json
=>  3.0.0-beta.3

package.json, src/component/date-picker/date-picker.component.html, src/component/date-picker/date-picker.component.ts, src/component/date-selector/date-format.pipe.ts, src/component/date-selector/date-selector.component.html, src/component/date-selector/date-selector.component.ts, src/component/date-selector/index.ts
fix: Set tab index to -1 for button to prevent unexpected behavior on form
fix: Call onTouchedCallback on input blur and value change
feat: Provide format for date-selector and a pipe to display the date accordingly
fix: Mask entry must not shift chars
=> Date picker improvments and bug fixes

src/component/date-picker/date-picker.component.html, src/component/date-picker/date-picker.component.scss, src/component/date-picker/date-picker.component.ts, src/component/date-picker/readme.md
Add a button as mat-suffix for mat-date-picker as shortcut to select the current date
=> Date component add current date button

src/component/editor/deja-editor.component.ts, src/component/editor/readme.md
Fix get and replace word at cursor position
=> CKEditor Search word and replace

src/component/editor/deja-editor.component.scss, src/component/editor/deja-editor.component.ts
Lateral scrollbar was always displayed
=> DejaEditor Lateral scrollbar

src/component/editor/deja-editor.component.ts
Init ckeditor even if the component is not on DOM
=> Fix DejaEditorComponent

src/component/date-picker/date-picker.component.scss
DatePicker actions vertical alignment with the input field
=> DatePicker actions vertical alignment

src/component/combo-list/component/combo-list-actionbar/combo-list-actionbar.component.html
If the combo list is placed inside a form, using the button submit it.
=> fix(DejaComboList) button in combo-list should not submit form

src/component/tag/tag.component.html, src/component/tag/tag.component.ts
Report of https://github.com/DSI-HUG/dejajs-components/pull/465 to version 4.x.x
=> Fix tag update (v 4.x.x)

projects/deja-js/component/date-picker/date-picker.component.ts
Place the cursor at the beginning of the input if empty.
=> DejaDatePicker

src/component/date-picker/date-picker.component.ts
Place the cursor at the beginning of the input if empty.
=> [4.x.x] DejaDatePicker

projects/deja-js/component/numeric-stepper/numeric-stepper.component.html, projects/deja-js/component/numeric-stepper/numeric-stepper.component.ts, src/app/numeric-stepper/numeric-stepper-demo.component.html
add possibility to hide steppers button
=> hide steppers

projects/deja-js/component/popup/_popup-theme.scss, projects/deja-js/component/popup/model/popup-config.model.ts, src/app/popup/popup-demo.ts
=> feat(PopupToolbar): Add orange as available color for pop-up toolbar

projects/deja-js/component/circular-picker/circular-picker.component.ts, projects/deja-js/component/message-box/_message-box-theme.scss, projects/deja-js/component/message-box/message-box.component.scss, projects/deja-js/component/message-box/readme.md, src/app/message-box/message-box-demo.html, src/app/message-box/message-box-demo.ts
* to use it, add the `light` attribute to the component when calling in html
=> feat(): message-box now have a light mode

projects/deja-js/component/popup/component/popup-advanced/popup-advanced.component.html, projects/deja-js/component/popup/component/popup-advanced/popup-advanced.component.ts, projects/deja-js/component/popup/component/popup-tray/popup-tray.component.ts, projects/deja-js/component/popup/model/popup-config.model.ts
* Add property config to hide from tray component
* After dragging window, update dialog position properties to fix fullscreen mode
=> fix(popup): update dialog position on dragEnded (DEJS-1004)

projects/deja-js/component/popup/component/popup-tray/popup-tray.component.ts
=> fix(popup-tray): avoid NPE on dialog without componentInstance

projects/deja-js/component/editor/deja-editor.component.ts
- use subject to trigger focus, disable, change, writeValue processing
=> fix(editor): wait editor ready before applying focus (DEJS-1066)
